---
output:
  pdf_document: default
  html_document: default
---

# 1.	Using July through October daily-high-temperature data for Atlanta for 1996 through 2015, use a CUSUM approach to identify when unofficial summer ends (i.e., when the weather starts cooling off) each year.  You can get the data that you need from the file temps.txt or online, for example at http://www.iweathernet.com/atlanta-weather-records  or https://www.wunderground.com/history/airport/KFTY/2015/7/1/CustomHistory.html .  You can use R if you’d like, but it’s straightforward enough that an Excel spreadsheet can easily do the job too.

# For the first part, I am following the below approach
a) Firstly, to get the mean value (mu) for CUSUM approach, I am considering average of July month's data every year as the mean for that year. I am using this month since visually, the temperature seems to be hot for almost all days in July. So this will be a good set of data to average and set a standard mean.
b) With this mean value, we have to use CUSUM approach to observe a decrease in the temperatures over the days every year to identify the unofficial end of summer every year.
c) For a start, I take C = 0.5 * Standard Deviation (of the temperatures in the month of July).
T = 5* Standard Deviation (of the temperatures in the month of July).
d) With these values, I use the CUSUM approach formula to compute detecting a decrease.

st = max{0, st-1 + (mu - xt - C)}
Change Detected , if St >= T

# Please refer to the attached excel sheet for calculations and results.
# temps  - This sheet contains the actual temperatures from the data file
# Summer_end - This sheet contains the calculations in excel to compute the CUSUM change detector. 
Since with the initial C and T values, there were some false positives, the final C and T value I have arrived at is
C = 5, T=20 for this model.
# Summer_end_results - This sheet contains the un-official summer end dates for each year from the data.

Note that the cells exceeding the threshold are colour coded which gives a good visual interpretation of the change. There are false positives with these parameters too, but increasing the value of C further, might end up in false negatives, and hence I played around upto 1* SD for C.

The first week of September is an average period of un-official summer end considering all years.

#                       QUESTION 6.2  (ii)
# 2.	Use a CUSUM approach to make a judgment of whether Atlanta’s summer climate has gotten warmer in that time (and if so, when).

# For this question, I have followed the below approach.
a) In this case, we are trying to observe if the temperature got warmer over a specific period of time. Since we know the un-official summer period from the above calculation, we could use the average of those dates as the average temperature of summer period every year, and then use this to detect an increase over the years.
b) mu = average of un-official SUmmer period (For Eg, for 2000, summer ended on 31-Aug. I would average all tempratures from 1-JUL to 31-AUG for this year's average warm temperature.)
c) Follow the same approach for CUSUM to start with C and T values based on the SD's of the above to detect change.
d) Since this is an increase that we are detecting, I would use the below formula:

st = max{0, st-1 + (xt - mu -C)}
Change detected, when st >= T

# Please refer to the attached excel sheet for calculations and results
# temps  - This sheet contains the actual temperatures from the data file
# Warmer_Analysis - This sheet holds the calculations in excel to compute the CUSUM change detector. 
The final values of C and T used are (C = 2, T = 22)

# Observation
Based on this, the temperature does not seem to get warmer constantly for every period, but there are a few very warm outstanding periods that can be detected.

For Eg. 4th August of 2009 and 2010 was much warmer than the average temperatures of this day.

Similarly, 18th and 19th Aug were very warm days for years 2007 - 2011.

Please refer to the colour coded days in the excel showing the change detected.
